name: CI tests

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: 0 6 * * 4

env:
  DB_ENDPOINT: 'http://localhost:8529'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [^9.0, ^10.0]
        php: [8.1, 8.2, 8.3]
        arangodb: [3.10, 3.11]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 9.*
            testbench: ^7.0
        exclude:
          - laravel: 10.*
            php: 8.0
    name:  QA L ${{ matrix.laravel }} / P ${{ matrix.php }} / A ${{ matrix.arangodb }}

    services:
      arangodb:
        image: arangodb:${{ matrix.arangodb }}
        ports:
          - 8529:8529
        env:
          ARANGO_NO_AUTH: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Prepare test database
        run: |
          chmod +x "${GITHUB_WORKSPACE}/bin/prepare-test-db.sh"
          "${GITHUB_WORKSPACE}/bin/prepare-test-db.sh"

      - name: Run all QA tests
        if: ${{ always() }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/bin/qa.sh"
          "${GITHUB_WORKSPACE}/bin/qa.sh"
        env:
          ARANGODB_VERSION: ${{ matrix.arangodb }}
